// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2nd1tTCeyREODfVF_eWSRAS_5s7RoepA',
    appId: '1:604207050690:web:756caf2b058a808405305b',
    messagingSenderId: '604207050690',
    projectId: 'hello123helo',
    authDomain: 'hello123helo.firebaseapp.com',
    databaseURL: 'https://hello123helo-default-rtdb.firebaseio.com',
    storageBucket: 'hello123helo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxhO0ZBJPLQI0ynsnpFY34YuL16VRDx4A',
    appId: '1:604207050690:android:996500658cd6cb5a05305b',
    messagingSenderId: '604207050690',
    projectId: 'hello123helo',
    databaseURL: 'https://hello123helo-default-rtdb.firebaseio.com',
    storageBucket: 'hello123helo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASykcn2hm5LoEo4T-w7IJTIeXm13cxNAg',
    appId: '1:604207050690:ios:80180bb40c24061d05305b',
    messagingSenderId: '604207050690',
    projectId: 'hello123helo',
    databaseURL: 'https://hello123helo-default-rtdb.firebaseio.com',
    storageBucket: 'hello123helo.appspot.com',
    iosClientId: '604207050690-snbi2nkdqce9rb63t4k4tboh6at1v6sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASykcn2hm5LoEo4T-w7IJTIeXm13cxNAg',
    appId: '1:604207050690:ios:80180bb40c24061d05305b',
    messagingSenderId: '604207050690',
    projectId: 'hello123helo',
    databaseURL: 'https://hello123helo-default-rtdb.firebaseio.com',
    storageBucket: 'hello123helo.appspot.com',
    iosClientId: '604207050690-snbi2nkdqce9rb63t4k4tboh6at1v6sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sir',
  );
}
